spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: augu
    password: 123456
  redis:
    host: 127.0.0.1


server:
  port: 8081
